onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_white_ballance_corrector/video_i/aclk
add wave -noupdate /tb_white_ballance_corrector/video_i/aresetn
add wave -noupdate /tb_white_ballance_corrector/video_i/tvalid
add wave -noupdate /tb_white_ballance_corrector/video_i/tready
add wave -noupdate /tb_white_ballance_corrector/video_i/tdata
add wave -noupdate /tb_white_ballance_corrector/video_i/tstrb
add wave -noupdate /tb_white_ballance_corrector/video_i/tkeep
add wave -noupdate /tb_white_ballance_corrector/video_i/tlast
add wave -noupdate /tb_white_ballance_corrector/video_i/tid
add wave -noupdate /tb_white_ballance_corrector/video_i/tdest
add wave -noupdate /tb_white_ballance_corrector/video_i/tuser
add wave -noupdate /tb_white_ballance_corrector/video_o/aclk
add wave -noupdate /tb_white_ballance_corrector/video_o/aresetn
add wave -noupdate /tb_white_ballance_corrector/video_o/tvalid
add wave -noupdate /tb_white_ballance_corrector/video_o/tready
add wave -noupdate /tb_white_ballance_corrector/video_o/tdata
add wave -noupdate /tb_white_ballance_corrector/video_o/tstrb
add wave -noupdate /tb_white_ballance_corrector/video_o/tkeep
add wave -noupdate /tb_white_ballance_corrector/video_o/tlast
add wave -noupdate /tb_white_ballance_corrector/video_o/tid
add wave -noupdate /tb_white_ballance_corrector/video_o/tdest
add wave -noupdate /tb_white_ballance_corrector/video_o/tuser
add wave -noupdate /tb_white_ballance_corrector/DUT/wb_ctrl_i/mode
add wave -noupdate /tb_white_ballance_corrector/DUT/wb_ctrl_i/cal_stb
add wave -noupdate /tb_white_ballance_corrector/DUT/wb_ctrl_i/man_sel
add wave -noupdate /tb_white_ballance_corrector/DUT/wb_ctrl_i/man_coef
add wave -noupdate /tb_white_ballance_corrector/DUT/wb_ctrl_i/man_lock
add wave -noupdate /tb_white_ballance_corrector/DUT/clk_i
add wave -noupdate /tb_white_ballance_corrector/DUT/rst_i
add wave -noupdate /tb_white_ballance_corrector/DUT/gw_r_corr
add wave -noupdate /tb_white_ballance_corrector/DUT/gw_b_corr
add wave -noupdate /tb_white_ballance_corrector/DUT/r_r_corr
add wave -noupdate /tb_white_ballance_corrector/DUT/r_b_corr
add wave -noupdate /tb_white_ballance_corrector/DUT/man_r_corr
add wave -noupdate /tb_white_ballance_corrector/DUT/man_g_corr
add wave -noupdate /tb_white_ballance_corrector/DUT/man_b_corr
add wave -noupdate /tb_white_ballance_corrector/DUT/r_corr
add wave -noupdate /tb_white_ballance_corrector/DUT/g_corr
add wave -noupdate /tb_white_ballance_corrector/DUT/b_corr
add wave -noupdate /tb_white_ballance_corrector/DUT/r_fixed
add wave -noupdate /tb_white_ballance_corrector/DUT/g_fixed
add wave -noupdate /tb_white_ballance_corrector/DUT/b_fixed
add wave -noupdate /tb_white_ballance_corrector/DUT/balanced_r
add wave -noupdate /tb_white_ballance_corrector/DUT/balanced_g
add wave -noupdate /tb_white_ballance_corrector/DUT/balanced_b
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/clk_i
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/rst_i
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/r_corr_o
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/b_corr_o
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/r_sum
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/g_sum
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/b_sum
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/px_cnt
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/mean_calc_start
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/r_mean
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/g_mean
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/b_mean
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/r_mean_valid
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/g_mean_valid
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/b_mean_valid
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/g_mean_fixed
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/r_corr
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/b_corr
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/r_corr_valid
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_gw/b_corr_valid
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_r/clk_i
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_r/rst_i
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_r/r_corr_o
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_r/b_corr_o
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_r/r_max
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_r/g_max
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_r/b_max
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_r/g_max_fixed
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_r/corr_calc_start
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_r/r_corr
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_r/b_corr
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_r/r_corr_valid
add wave -noupdate /tb_white_ballance_corrector/DUT/awb_r/b_corr_valid
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {484574800 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 728
configure wave -valuecolwidth 147
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {4949585454 ps}
